import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import RoutApp from './Routing/RoutApp';
import AgeDecreaseApp from './AgeDecrease/AgeDecreaseApp';
import TwoWayBindApp from './TwoWayBinding/TwoWayBindApp';
ReactDOM.render(<TwoWayBindApp />, document.getElementById('root'));
registerServiceWorker();
